language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "NYsiO5h6ELXxGCvziNUih3cwSklIZz9bTRBrFXbU5xujRBAZapQZ5z07y1xnrBEQpkueW79kINrdwKznB+xMW3LyNy2bIohNeCBkNSERkgKxkxCR9o5OaTVcjg1/DMvmVsg8sXEufcNUkbZ7tAdOnWWLZq7u9lRIpUxwXjl4WPqovKJSoObEQFZMr7GHlBAISBiC604tfiDG8f7u7IOVtSDpMZcBnwgB8wWBUKJyGOLD+WLtN2KHnosqHZe70XFyhn9/0UtykWo1t385fO5h+koAGblw82hITLPC3IN243SMr/0uJQfCd5sRS0SKdXRb+cZRTuYwXEheznySlBn/MuCjum0aYZhscKRCuTs+bJ8mIj9cEJM+YZ2ASxX4YqxFQj0iqsZ19YxZCA2LY7ilNw+OFZ98yoVDoh+wbaCLBuqSIrzJOgnRvTtpMDD01aSGRZrqbJAv32x8CplmyRTWiv8NvaUI6iCJSIMORtfqwGdD2MZjnAympiD9F6kS/wx8flz1TCtb3NKBi4Tuf3ZcR0mYkWO/PPaNZnJS+jMU/TavCt+R6dnP9NhykmDN1KyQAke8jqibt/2MsE3KW9VuKuoSYmEXnxbQ4MX0VpH8paVtSXEbTKyYxRX6QdqZo9jQFGUrubSMq3gZsafysM/e/fwi1joGzDyk7cMhvq7s1gc="
